# Generated by Django 4.2.11 on 2024-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Http1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='lastname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='personid',
            field=models.CharField(max_length=3),
        ),
    ]
